# Generated by Django 2.0.3 on 2018-04-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('problem_name', models.TextField(null=True)),
                ('cog_model', models.TextField(null=True)),
                ('var_list', models.TextField(null=True)),
                ('brd', models.TextField(null=True)),
            ],
        ),
    ]
